name: Install and verify safe-chain
description: Installs safe-chain and verifies it is working correctly

runs:
  using: composite
  steps:
    - name: Install safe-chain
      shell: bash
      run: curl --fail --silent --show-error --retry 3 --location "https://github.com/AikidoSec/safe-chain/releases/download/${SAFECHAIN_VERSION}/install-safe-chain.sh" | sh -s -- --ci
      env:
        SAFECHAIN_VERSION: 1.5.11

    - name: Test safe-chain
      shell: bash
      # this must fail if safe-chain is working
      run: |
        npm safe-chain-verify
        ! npm install safe-chain-test
